package org.andot.account.entity;

import java.io.Serializable;
import java.util.Date;

public class Action implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer actionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String actionName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte actionType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.action_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String actionUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Integer menuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private String caption;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Byte disabled;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column action.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private Date deleteTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.action_id
     *
     * @return the value of action.action_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getActionId() {
        return actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.action_id
     *
     * @param actionId the value for action.action_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setActionId(Integer actionId) {
        this.actionId = actionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.action_name
     *
     * @return the value of action.action_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getActionName() {
        return actionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.action_name
     *
     * @param actionName the value for action.action_name
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setActionName(String actionName) {
        this.actionName = actionName == null ? null : actionName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.action_type
     *
     * @return the value of action.action_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getActionType() {
        return actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.action_type
     *
     * @param actionType the value for action.action_type
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setActionType(Byte actionType) {
        this.actionType = actionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.action_url
     *
     * @return the value of action.action_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getActionUrl() {
        return actionUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.action_url
     *
     * @param actionUrl the value for action.action_url
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setActionUrl(String actionUrl) {
        this.actionUrl = actionUrl == null ? null : actionUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.menu_id
     *
     * @return the value of action.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Integer getMenuId() {
        return menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.menu_id
     *
     * @param menuId the value for action.menu_id
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setMenuId(Integer menuId) {
        this.menuId = menuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.caption
     *
     * @return the value of action.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getCaption() {
        return caption;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.caption
     *
     * @param caption the value for action.caption
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setCaption(String caption) {
        this.caption = caption == null ? null : caption.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.disabled
     *
     * @return the value of action.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Byte getDisabled() {
        return disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.disabled
     *
     * @param disabled the value for action.disabled
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDisabled(Byte disabled) {
        this.disabled = disabled;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.create_time
     *
     * @return the value of action.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.create_time
     *
     * @param createTime the value for action.create_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.update_time
     *
     * @return the value of action.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.update_time
     *
     * @param updateTime the value for action.update_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column action.delete_time
     *
     * @return the value of action.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Date getDeleteTime() {
        return deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column action.delete_time
     *
     * @param deleteTime the value for action.delete_time
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDeleteTime(Date deleteTime) {
        this.deleteTime = deleteTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", actionId=").append(actionId);
        sb.append(", actionName=").append(actionName);
        sb.append(", actionType=").append(actionType);
        sb.append(", actionUrl=").append(actionUrl);
        sb.append(", menuId=").append(menuId);
        sb.append(", caption=").append(caption);
        sb.append(", disabled=").append(disabled);
        sb.append(", createTime=").append(createTime);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", deleteTime=").append(deleteTime);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Action other = (Action) that;
        return (this.getActionId() == null ? other.getActionId() == null : this.getActionId().equals(other.getActionId()))
            && (this.getActionName() == null ? other.getActionName() == null : this.getActionName().equals(other.getActionName()))
            && (this.getActionType() == null ? other.getActionType() == null : this.getActionType().equals(other.getActionType()))
            && (this.getActionUrl() == null ? other.getActionUrl() == null : this.getActionUrl().equals(other.getActionUrl()))
            && (this.getMenuId() == null ? other.getMenuId() == null : this.getMenuId().equals(other.getMenuId()))
            && (this.getCaption() == null ? other.getCaption() == null : this.getCaption().equals(other.getCaption()))
            && (this.getDisabled() == null ? other.getDisabled() == null : this.getDisabled().equals(other.getDisabled()))
            && (this.getCreateTime() == null ? other.getCreateTime() == null : this.getCreateTime().equals(other.getCreateTime()))
            && (this.getUpdateTime() == null ? other.getUpdateTime() == null : this.getUpdateTime().equals(other.getUpdateTime()))
            && (this.getDeleteTime() == null ? other.getDeleteTime() == null : this.getDeleteTime().equals(other.getDeleteTime()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getActionId() == null) ? 0 : getActionId().hashCode());
        result = prime * result + ((getActionName() == null) ? 0 : getActionName().hashCode());
        result = prime * result + ((getActionType() == null) ? 0 : getActionType().hashCode());
        result = prime * result + ((getActionUrl() == null) ? 0 : getActionUrl().hashCode());
        result = prime * result + ((getMenuId() == null) ? 0 : getMenuId().hashCode());
        result = prime * result + ((getCaption() == null) ? 0 : getCaption().hashCode());
        result = prime * result + ((getDisabled() == null) ? 0 : getDisabled().hashCode());
        result = prime * result + ((getCreateTime() == null) ? 0 : getCreateTime().hashCode());
        result = prime * result + ((getUpdateTime() == null) ? 0 : getUpdateTime().hashCode());
        result = prime * result + ((getDeleteTime() == null) ? 0 : getDeleteTime().hashCode());
        return result;
    }
}