package org.andot.account.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class PageElementCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public PageElementCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andPageElementIdIsNull() {
            addCriterion("page_element_id is null");
            return (Criteria) this;
        }

        public Criteria andPageElementIdIsNotNull() {
            addCriterion("page_element_id is not null");
            return (Criteria) this;
        }

        public Criteria andPageElementIdEqualTo(Integer value) {
            addCriterion("page_element_id =", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdNotEqualTo(Integer value) {
            addCriterion("page_element_id <>", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdGreaterThan(Integer value) {
            addCriterion("page_element_id >", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("page_element_id >=", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdLessThan(Integer value) {
            addCriterion("page_element_id <", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdLessThanOrEqualTo(Integer value) {
            addCriterion("page_element_id <=", value, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdIn(List<Integer> values) {
            addCriterion("page_element_id in", values, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdNotIn(List<Integer> values) {
            addCriterion("page_element_id not in", values, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdBetween(Integer value1, Integer value2) {
            addCriterion("page_element_id between", value1, value2, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementIdNotBetween(Integer value1, Integer value2) {
            addCriterion("page_element_id not between", value1, value2, "pageElementId");
            return (Criteria) this;
        }

        public Criteria andPageElementNameIsNull() {
            addCriterion("page_element_name is null");
            return (Criteria) this;
        }

        public Criteria andPageElementNameIsNotNull() {
            addCriterion("page_element_name is not null");
            return (Criteria) this;
        }

        public Criteria andPageElementNameEqualTo(String value) {
            addCriterion("page_element_name =", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameNotEqualTo(String value) {
            addCriterion("page_element_name <>", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameGreaterThan(String value) {
            addCriterion("page_element_name >", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameGreaterThanOrEqualTo(String value) {
            addCriterion("page_element_name >=", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameLessThan(String value) {
            addCriterion("page_element_name <", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameLessThanOrEqualTo(String value) {
            addCriterion("page_element_name <=", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameLike(String value) {
            addCriterion("page_element_name like", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameNotLike(String value) {
            addCriterion("page_element_name not like", value, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameIn(List<String> values) {
            addCriterion("page_element_name in", values, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameNotIn(List<String> values) {
            addCriterion("page_element_name not in", values, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameBetween(String value1, String value2) {
            addCriterion("page_element_name between", value1, value2, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementNameNotBetween(String value1, String value2) {
            addCriterion("page_element_name not between", value1, value2, "pageElementName");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeIsNull() {
            addCriterion("page_element_code is null");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeIsNotNull() {
            addCriterion("page_element_code is not null");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeEqualTo(String value) {
            addCriterion("page_element_code =", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeNotEqualTo(String value) {
            addCriterion("page_element_code <>", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeGreaterThan(String value) {
            addCriterion("page_element_code >", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeGreaterThanOrEqualTo(String value) {
            addCriterion("page_element_code >=", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeLessThan(String value) {
            addCriterion("page_element_code <", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeLessThanOrEqualTo(String value) {
            addCriterion("page_element_code <=", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeLike(String value) {
            addCriterion("page_element_code like", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeNotLike(String value) {
            addCriterion("page_element_code not like", value, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeIn(List<String> values) {
            addCriterion("page_element_code in", values, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeNotIn(List<String> values) {
            addCriterion("page_element_code not in", values, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeBetween(String value1, String value2) {
            addCriterion("page_element_code between", value1, value2, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementCodeNotBetween(String value1, String value2) {
            addCriterion("page_element_code not between", value1, value2, "pageElementCode");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeIsNull() {
            addCriterion("page_element_type is null");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeIsNotNull() {
            addCriterion("page_element_type is not null");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeEqualTo(Byte value) {
            addCriterion("page_element_type =", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeNotEqualTo(Byte value) {
            addCriterion("page_element_type <>", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeGreaterThan(Byte value) {
            addCriterion("page_element_type >", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("page_element_type >=", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeLessThan(Byte value) {
            addCriterion("page_element_type <", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeLessThanOrEqualTo(Byte value) {
            addCriterion("page_element_type <=", value, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeIn(List<Byte> values) {
            addCriterion("page_element_type in", values, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeNotIn(List<Byte> values) {
            addCriterion("page_element_type not in", values, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeBetween(Byte value1, Byte value2) {
            addCriterion("page_element_type between", value1, value2, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("page_element_type not between", value1, value2, "pageElementType");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlIsNull() {
            addCriterion("page_element_url is null");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlIsNotNull() {
            addCriterion("page_element_url is not null");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlEqualTo(String value) {
            addCriterion("page_element_url =", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlNotEqualTo(String value) {
            addCriterion("page_element_url <>", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlGreaterThan(String value) {
            addCriterion("page_element_url >", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlGreaterThanOrEqualTo(String value) {
            addCriterion("page_element_url >=", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlLessThan(String value) {
            addCriterion("page_element_url <", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlLessThanOrEqualTo(String value) {
            addCriterion("page_element_url <=", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlLike(String value) {
            addCriterion("page_element_url like", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlNotLike(String value) {
            addCriterion("page_element_url not like", value, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlIn(List<String> values) {
            addCriterion("page_element_url in", values, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlNotIn(List<String> values) {
            addCriterion("page_element_url not in", values, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlBetween(String value1, String value2) {
            addCriterion("page_element_url between", value1, value2, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andPageElementUrlNotBetween(String value1, String value2) {
            addCriterion("page_element_url not between", value1, value2, "pageElementUrl");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNull() {
            addCriterion("disabled is null");
            return (Criteria) this;
        }

        public Criteria andDisabledIsNotNull() {
            addCriterion("disabled is not null");
            return (Criteria) this;
        }

        public Criteria andDisabledEqualTo(String value) {
            addCriterion("disabled =", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotEqualTo(String value) {
            addCriterion("disabled <>", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThan(String value) {
            addCriterion("disabled >", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledGreaterThanOrEqualTo(String value) {
            addCriterion("disabled >=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThan(String value) {
            addCriterion("disabled <", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLessThanOrEqualTo(String value) {
            addCriterion("disabled <=", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledLike(String value) {
            addCriterion("disabled like", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotLike(String value) {
            addCriterion("disabled not like", value, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledIn(List<String> values) {
            addCriterion("disabled in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotIn(List<String> values) {
            addCriterion("disabled not in", values, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledBetween(String value1, String value2) {
            addCriterion("disabled between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andDisabledNotBetween(String value1, String value2) {
            addCriterion("disabled not between", value1, value2, "disabled");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNull() {
            addCriterion("create_time is null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIsNotNull() {
            addCriterion("create_time is not null");
            return (Criteria) this;
        }

        public Criteria andCreateTimeEqualTo(Date value) {
            addCriterion("create_time =", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotEqualTo(Date value) {
            addCriterion("create_time <>", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThan(Date value) {
            addCriterion("create_time >", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("create_time >=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThan(Date value) {
            addCriterion("create_time <", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeLessThanOrEqualTo(Date value) {
            addCriterion("create_time <=", value, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeIn(List<Date> values) {
            addCriterion("create_time in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotIn(List<Date> values) {
            addCriterion("create_time not in", values, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeBetween(Date value1, Date value2) {
            addCriterion("create_time between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andCreateTimeNotBetween(Date value1, Date value2) {
            addCriterion("create_time not between", value1, value2, "createTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNull() {
            addCriterion("update_time is null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIsNotNull() {
            addCriterion("update_time is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeEqualTo(Date value) {
            addCriterion("update_time =", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotEqualTo(Date value) {
            addCriterion("update_time <>", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThan(Date value) {
            addCriterion("update_time >", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("update_time >=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThan(Date value) {
            addCriterion("update_time <", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeLessThanOrEqualTo(Date value) {
            addCriterion("update_time <=", value, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeIn(List<Date> values) {
            addCriterion("update_time in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotIn(List<Date> values) {
            addCriterion("update_time not in", values, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeBetween(Date value1, Date value2) {
            addCriterion("update_time between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andUpdateTimeNotBetween(Date value1, Date value2) {
            addCriterion("update_time not between", value1, value2, "updateTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNull() {
            addCriterion("delete_time is null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIsNotNull() {
            addCriterion("delete_time is not null");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeEqualTo(Date value) {
            addCriterion("delete_time =", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotEqualTo(Date value) {
            addCriterion("delete_time <>", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThan(Date value) {
            addCriterion("delete_time >", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("delete_time >=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThan(Date value) {
            addCriterion("delete_time <", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeLessThanOrEqualTo(Date value) {
            addCriterion("delete_time <=", value, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeIn(List<Date> values) {
            addCriterion("delete_time in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotIn(List<Date> values) {
            addCriterion("delete_time not in", values, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeBetween(Date value1, Date value2) {
            addCriterion("delete_time between", value1, value2, "deleteTime");
            return (Criteria) this;
        }

        public Criteria andDeleteTimeNotBetween(Date value1, Date value2) {
            addCriterion("delete_time not between", value1, value2, "deleteTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_element
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 10 10:32:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table page_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}