package org.andot.account.entity;

import java.util.ArrayList;
import java.util.List;

public class ResourcesGroupsCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public ResourcesGroupsCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andResGroupIdIsNull() {
            addCriterion("res_group_id is null");
            return (Criteria) this;
        }

        public Criteria andResGroupIdIsNotNull() {
            addCriterion("res_group_id is not null");
            return (Criteria) this;
        }

        public Criteria andResGroupIdEqualTo(Integer value) {
            addCriterion("res_group_id =", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdNotEqualTo(Integer value) {
            addCriterion("res_group_id <>", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdGreaterThan(Integer value) {
            addCriterion("res_group_id >", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("res_group_id >=", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdLessThan(Integer value) {
            addCriterion("res_group_id <", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdLessThanOrEqualTo(Integer value) {
            addCriterion("res_group_id <=", value, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdIn(List<Integer> values) {
            addCriterion("res_group_id in", values, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdNotIn(List<Integer> values) {
            addCriterion("res_group_id not in", values, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdBetween(Integer value1, Integer value2) {
            addCriterion("res_group_id between", value1, value2, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResGroupIdNotBetween(Integer value1, Integer value2) {
            addCriterion("res_group_id not between", value1, value2, "resGroupId");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIsNull() {
            addCriterion("resources_type is null");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIsNotNull() {
            addCriterion("resources_type is not null");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeEqualTo(Byte value) {
            addCriterion("resources_type =", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotEqualTo(Byte value) {
            addCriterion("resources_type <>", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeGreaterThan(Byte value) {
            addCriterion("resources_type >", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("resources_type >=", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeLessThan(Byte value) {
            addCriterion("resources_type <", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeLessThanOrEqualTo(Byte value) {
            addCriterion("resources_type <=", value, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeIn(List<Byte> values) {
            addCriterion("resources_type in", values, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotIn(List<Byte> values) {
            addCriterion("resources_type not in", values, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeBetween(Byte value1, Byte value2) {
            addCriterion("resources_type between", value1, value2, "resourcesType");
            return (Criteria) this;
        }

        public Criteria andResourcesTypeNotBetween(Byte value1, Byte value2) {
            addCriterion("resources_type not between", value1, value2, "resourcesType");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resources_groups
     *
     * @mbggenerated do_not_delete_during_merge Thu Jan 10 10:32:10 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}