package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.ActionOperatePower;
import org.andot.account.entity.ActionOperatePowerCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ActionOperatePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(ActionOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(ActionOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer actionPowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(ActionOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(ActionOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ActionOperatePower> selectByExampleWithRowbounds(ActionOperatePowerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ActionOperatePower> selectByExample(ActionOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    ActionOperatePower selectByPrimaryKey(Integer actionPowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ActionOperatePower record, @Param("example") ActionOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") ActionOperatePower record, @Param("example") ActionOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(ActionOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table action_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(ActionOperatePower record);
}