package org.andot.account.mapper;

import org.andot.account.domain.UniSafeUserDetails;
import org.andot.account.entity.BaseUser;
import org.andot.account.entity.BaseUserCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

import java.util.List;

@Mapper
@Repository
public interface BaseUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int countByExample(BaseUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int deleteByExample(BaseUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int insert(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int insertSelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    List<BaseUser> selectByExampleWithRowbounds(BaseUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    List<BaseUser> selectByExample(BaseUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    BaseUser selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") BaseUser record, @Param("example") BaseUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int updateByExample(@Param("record") BaseUser record, @Param("example") BaseUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int updateByPrimaryKeySelective(BaseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table base_user
     *
     * @mbggenerated Sun Feb 10 20:08:14 CST 2019
     */
    int updateByPrimaryKey(BaseUser record);

    /***
     * 根据用户id获取用户传输信息
     * @param userId
     * @return
     */
    UniSafeUserDetails getUserDetails(@Param("userId") Integer userId);
}