package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.ElementOperatePower;
import org.andot.account.entity.ElementOperatePowerCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ElementOperatePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(ElementOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(ElementOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer elementPowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(ElementOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(ElementOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ElementOperatePower> selectByExampleWithRowbounds(ElementOperatePowerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ElementOperatePower> selectByExample(ElementOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    ElementOperatePower selectByPrimaryKey(Integer elementPowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ElementOperatePower record, @Param("example") ElementOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") ElementOperatePower record, @Param("example") ElementOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(ElementOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table element_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(ElementOperatePower record);
}