package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.MenuElement;
import org.andot.account.entity.MenuElementCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MenuElementMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(MenuElementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(MenuElementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer menuElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(MenuElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(MenuElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<MenuElement> selectByExampleWithRowbounds(MenuElementCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<MenuElement> selectByExample(MenuElementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    MenuElement selectByPrimaryKey(Integer menuElementId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") MenuElement record, @Param("example") MenuElementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") MenuElement record, @Param("example") MenuElementCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(MenuElement record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_element
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(MenuElement record);
}