package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.Menu;
import org.andot.account.entity.MenuCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer menuActionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<Menu> selectByExampleWithRowbounds(MenuCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<Menu> selectByExample(MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    Menu selectByPrimaryKey(Integer menuActionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Menu record, @Param("example") MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") Menu record, @Param("example") MenuCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table menu_action
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(Menu record);
}