package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.OrganUser;
import org.andot.account.entity.OrganUserCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OrganUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(OrganUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(OrganUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer organUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(OrganUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(OrganUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<OrganUser> selectByExampleWithRowbounds(OrganUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<OrganUser> selectByExample(OrganUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    OrganUser selectByPrimaryKey(Integer organUserId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") OrganUser record, @Param("example") OrganUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") OrganUser record, @Param("example") OrganUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(OrganUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ_user
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(OrganUser record);
}