package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.Organ;
import org.andot.account.entity.OrganCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface OrganMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(OrganCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(OrganCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer organId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<Organ> selectByExampleWithRowbounds(OrganCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<Organ> selectByExample(OrganCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    Organ selectByPrimaryKey(Integer organId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") Organ record, @Param("example") OrganCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") Organ record, @Param("example") OrganCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(Organ record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organ
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(Organ record);
}