package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.ResourcesGroups;
import org.andot.account.entity.ResourcesGroupsCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface ResourcesGroupsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer resGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(ResourcesGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(ResourcesGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ResourcesGroups> selectByExampleWithBLOBsWithRowbounds(ResourcesGroupsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ResourcesGroups> selectByExampleWithBLOBs(ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ResourcesGroups> selectByExampleWithRowbounds(ResourcesGroupsCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<ResourcesGroups> selectByExample(ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    ResourcesGroups selectByPrimaryKey(Integer resGroupId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") ResourcesGroups record, @Param("example") ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") ResourcesGroups record, @Param("example") ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") ResourcesGroups record, @Param("example") ResourcesGroupsCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(ResourcesGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(ResourcesGroups record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resources_groups
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(ResourcesGroups record);
}