package org.andot.account.mapper;

import java.util.List;
import org.andot.account.entity.RoleOperatePower;
import org.andot.account.entity.RoleOperatePowerCriteria;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;
import org.springframework.stereotype.Repository;

@Mapper
@Repository
public interface RoleOperatePowerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int countByExample(RoleOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByExample(RoleOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int deleteByPrimaryKey(Integer rolePowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insert(RoleOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int insertSelective(RoleOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<RoleOperatePower> selectByExampleWithRowbounds(RoleOperatePowerCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    List<RoleOperatePower> selectByExample(RoleOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    RoleOperatePower selectByPrimaryKey(Integer rolePowerId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoleOperatePower record, @Param("example") RoleOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByExample(@Param("record") RoleOperatePower record, @Param("example") RoleOperatePowerCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKeySelective(RoleOperatePower record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table role_operate_power
     *
     * @mbggenerated Thu Jan 10 10:32:10 CST 2019
     */
    int updateByPrimaryKey(RoleOperatePower record);
}