server:
  port: 8080
eureka:
  instance:
    hostname: 192.168.196.74 #实例主机名
  # 说明了不是客户端而是一个服务端
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8090/eureka/,http://${eureka.instance.hostname}:8070/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  profiles: dev
  application:
    name: eurka-server-ball